# Generated by Django 4.2.13 on 2024-06-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
